### ISSUE TITLE
Unable compile 'com.wang.avi:library:2.1.3'

### ISSUE THREAD

**Issue by Jendorski** [81813780/AVLoadingIndicatorView#105]
Hello,

I have been trying to compile 'com.wang.avi:library:2.1.3' for some time now, to no avail, 
i use Gradle 2.3.3, 
i git clone the 'https://github.com/81813780/AVLoadingIndicatorView/' then 
tried to import as a module and 
added include ':AVLoadingIndicatorView:library:' to the settings.gradle, did not work,
added the maven { url "https://jitpack.io" } did not work.

Is there something else i am missing?.

**Comment by Jendorski** [comment]
It was my fault, i removed jcenter() from the build.gradle.

**Comment by dev-varaha** [comment]
this version is working fine in my app
    implementation 'com.wang.avi:library:1.0.5'

**Comment by alcadiosystem** [comment]
> this version is working fine in my app implementation 'com.wang.avi:library:1.0.5'
