### ISSUE TITLE
FadeOut and In animation

### ISSUE THREAD

**Issue by ravenet** [81813780/AVLoadingIndicatorView#11]
Hi,

I am trying to set fade in and out animation with this indicators, but  VISIBLE and GONE is not working when set startAnimation to control.

Could you fix the issue.

Thanks

**Comment by 81813780** [comment]
It's works

![qq 20151218123532](https://cloud.githubusercontent.com/assets/2297803/11889408/fa1fc5ba-a583-11e5-996d-b8e0905e7fa8.png)

**Comment by ravenet** [comment]
Hi,

Thank you and I will check my code with your reference code. Thanks again

**Comment by 81813780** [comment]
You are welcome :)  If you have any problem,welcome to tell me.
