### ISSUE TITLE
AVLoadingIndicatorView memory leak

### ISSUE THREAD

**Issue by IgorB10** [81813780/AVLoadingIndicatorView#12]
Hello! I noticed that AVLoadingIndicatorView never release a reference to target View. That why activities will never be garbage collected.

I built a simple application with 2 activities. Second(LeakActivity) just have animation 
First:
![screen shot 2015-11-19 at 12 41 52 am](https://cloud.githubusercontent.com/assets/2640423/11256737/680512b4-8e56-11e5-8c27-4990299dfb05.png)
Second:
![screen shot 2015-11-19 at 12 41 43 am](https://cloud.githubusercontent.com/assets/2640423/11256750/6c111dda-8e56-11e5-9aef-c519d6969a5b.png)

and after open and close LeakActvity we can see:
![screen shot 2015-11-19 at 12 38 01 am](https://cloud.githubusercontent.com/assets/2640423/11256767/8520940e-8e56-11e5-9ef5-05f3a77528ff.png)

and a root to GC
![screen shot 2015-11-19 at 12 38 11 am](https://cloud.githubusercontent.com/assets/2640423/11256774/90c8d492-8e56-11e5-98be-4f705f28604a.png)

**Comment by 81813780** [comment]
I know what you mean,I'll check it later.

**Comment by 81813780** [comment]
I have fixed it, you can help me to test it.

**Comment by IgorB10** [comment]
I will test your fix tomorrow. 
But I fixed it just added in BaseIndicatorController.java

private Weakreference<View> mTarget;

instead of

private View mTarget;

**Comment by 81813780** [comment]
use Weakreference can also handle this. 
Thanks for your test,If any problem,welcome to tell me.

**Comment by IgorB10** [comment]
Sure :) Thank you!

**Comment by IgorB10** [comment]
Hi, @81813780 !
Sorry for a big delay, but I really like your library. I was wondering, what if we will apply my suggestion and we will remove stop animation method and add "Weakreference" to the target what also will resolve leak. I can prepare to merge request if you agree.

Thank you!

**Comment by 81813780** [comment]
I don't really understand what you mean , but welcome to send PR :)
