### ISSUE TITLE
Could not find com.wang.avi:library:2.1.3.

### ISSUE THREAD

**Issue by imTefa** [81813780/AVLoadingIndicatorView#134]
I couldn't compile this lib after removing jcenter because of deprecation
is there a new version published else where ?

**Comment by blackhofc** [comment]
Add this on build.gradle 
implementation 'com.github.chenzj-king:AVLoadingIndicatorView:2.1.1'

**Comment by maitrungduc1410** [comment]
> Add this on build.gradle implementation 'com.github.chenzj-king:AVLoadingIndicatorView:2.1.1'

this one doesn't work at the moment

**Comment by maitrungduc1410** [comment]
I have to publish this library to my own maven central repo, it should be stable now.

`implementation io.github.maitrungduc1410:AVLoadingIndicatorView:2.1.5`

See more: https://github.com/maitrungduc1410/AVLoadingIndicatorView

**Comment by dungpv04** [comment]
> I have to publish this library to my own maven central repo, it should be stable now.
> 
> `implementation io.github.maitrungduc1410:AVLoadingIndicatorView:2.1.4`

cam on bro nhieu :)))

**Comment by Tusar0003** [comment]
> I have to publish this library to my own maven central repo, it should be stable now.
> 
> `implementation io.github.maitrungduc1410:AVLoadingIndicatorView:2.1.4`

thanks brother
