### ISSUE TITLE
Espresso error: AppNotIdleException

### ISSUE THREAD

**Issue by VictorAlbertos** [81813780/AVLoadingIndicatorView#16]
Hi.

I’m having troubles using your library with ui testing provided by [Espresso](https://google.github.io/android-testing-support-library/docs/espresso/setup/). If I create an instance of AVLoadingIndicatorView, the test get stuck until the next exception is thrown:  

Caused by: android.support.test.espresso.AppNotIdleException: Looped for 71216 iterations over 60 SECONDS. The following Idle Conditions failed .
at android.support.test.espresso.IdlingPolicy.handleTimeout(IdlingPolicy.java:61)
at android.support.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:477)

It does not matter if I set the visibility of the view to View.Invisible or View.Gone before continuing the text, the error still happens. 

I think the problem is related [with this topic](http://stackoverflow.com/questions/29550508/espresso-freezing-on-view-with-looping-animation).

The library is so cool, but currently I can’t use because of this. Because if I use your view I can’t perform integration testing with Espresso. Maybe there is some workaround to prevent this behaviour… I don’t know.

Thanks!

**Comment by 81813780** [comment]
I thought this error probably was Espresso to support test infinite animations not well.
I noticed Espresso setup instructions 

![qq 20151218120325](https://cloud.githubusercontent.com/assets/2297803/11889057/6f5da4dc-a57f-11e5-81b2-967352a6c8d3.png)

Then I test it use Espresso without AVLoadingIndicatorView:

![qq 20151218120659](https://cloud.githubusercontent.com/assets/2297803/11889090/06a1452e-a580-11e5-9456-b03ff2291e97.png)  

![qq 20151218120708](https://cloud.githubusercontent.com/assets/2297803/11889095/11365f9c-a580-11e5-933d-0a0e5b6c2b69.png)  

![qq 20151218120711](https://cloud.githubusercontent.com/assets/2297803/11889100/19de9286-a580-11e5-9e18-7593804be315.png)

it's same error:AppNotIdleException

I didn't used Espresso before,Maybe I guess wrong. I will check this error again when I'm free.And Also hope you can provide more details about this.
