### ISSUE TITLE
Error xml app:indicator

### ISSUE THREAD

**Issue by LuisDominguez** [81813780/AVLoadingIndicatorView#17]
Hello, when im add a 
app:indicator on xml file in android studio 
make a error
app:indicator="BallClipRotate"
on run:
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/home/luis/Android/Sdk/build-tools/22.0.1/aapt'' finished with non-zero exit value 1

On preview:

"BallClipRotate" in attribute "indicator" is not a valid integer

**Comment by 81813780** [comment]
I suggest you try to update to the latest version .

**Comment by talhahasanzia** [comment]
I am using latest version: 2.1.3 and its showing me this error.
My min API: 19
Target API: 25
