### ISSUE TITLE
How To Add footer list ?

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [81813780/AVLoadingIndicatorView#30]
I appreciated your project.I want to add footer list. my problem is that this view cover all the page width and It do not accept the size that I put for it.

I have used indicator = BallPulseSync for loading in list view footer(in list pagination).
the problem is that the balls fill the list's width.
my question is how to set size for balls?

**Comment by 81813780** [comment]
#13 You can look this .
or this library XRecyclerView[https://github.com/jianghejie/XRecyclerView] .
