### ISSUE TITLE
最新的小米的6.0.1的系统，显示不出来啊，就一个白框

### ISSUE THREAD

**Issue by kailaisi** [81813780/AVLoadingIndicatorView#32]

**Comment by 81813780** [comment]
我自己用的就是小米4，最新的6.0.1的系统，无论是demo还是引用显示都无问题。有空我把图传上来，建议你再检查检查吧。

**Comment by kailaisi** [comment]
我是inflate出来的view，然后放在了dialog中，我再看看是什么问题吧

**Comment by 81813780** [comment]
那6.0.1以下可以吗？

**Comment by 81813780** [comment]
有时间的话，我可以按照你说的方式，测试一下试试。

**Comment by kailaisi** [comment]
小米4系统升级之前的4.4.2的系统没问题，后来升级了，发现了这个问题。。
