### ISSUE TITLE
1.0.4 crash

### ISSUE THREAD

**Issue by alcntml** [81813780/AVLoadingIndicatorView#33]
java.lang.ClassNotFoundException: Didn't find class "android.support.v7.widget.TintManager"

But, 1.0.1 working.

**Comment by 81813780** [comment]
AVLoadingIndicatorView didn't use  "android.support.v7.widget.TintManager" , So I thought this carsh was not caused by AVLoadingIndicatorView  .  I suggest you check it again , Or can you provide more details?

**Comment by Dhaval2404** [comment]
All the support library have to be the same version. Change your support library version to **23.2.0**.

`     compile 'com.android.support:appcompat-v7:23.2.0'
`
