### ISSUE TITLE
Animation lock in recyclerView

### ISSUE THREAD

**Issue by Shargotth** [81813780/AVLoadingIndicatorView#34]
When the AVLoader is in a layout used in a recyclerView, the animation stop when it is scrolled out and in of the screen.

Any idea how to fix it?

**Comment by Shargotth** [comment]
I fixed it myself by adding : 

```
myAVLoaderView.setVisibility(View.GONE)
myAVLoaderView.setVisibility(View.VISIBLE)
```
inside my method `onBindViewHolder`.

**Comment by Dhaval2404** [comment]
I am also facing the same issue. I have integrated `AVLoadingIndicatorView` inside `GridView`.

As soon as i set visibility to `View.VISIBLE`, my whole UI get freeze. When i remove  `AVLoadingIndicatorView` from UI or set visibility as `View.GONE`, everything work fine. So it's seems some problem in `AVLoadingIndicatorView`.

Any help will be appreciated.

**Comment by 81813780** [comment]
See #45
