### ISSUE TITLE
set duration

### ISSUE THREAD

**Issue by juanmartinbernal** [81813780/AVLoadingIndicatorView#36]
hi, 

IS possible change duration to animation loading?

**Comment by alivebao** [comment]
I think you can set it by setVisibility(View.VISIBLE)/setVisibility(View.GONE) in a timer

**Comment by Kiarasht** [comment]
I guess you could create a Timer and have "setVisibility(View.GONE);" whenever the duration is reached.

**Comment by 81813780** [comment]
See #45
