### ISSUE TITLE
Indicator Color not working

### ISSUE THREAD

**Issue by mkiisoft** [81813780/AVLoadingIndicatorView#38]
Hello, dev!

I try to use app:indicator_color="your color" with no luck... I've try it with hex "000000" (not working), @color/black (not working). "0xFF000000" (also not working).

Any idea? Also It would be great if we can change the color by code, like: mProgress.setProgressColor(int color) or similar.

**Comment by yon86** [comment]
@mkiisoft did u solve this problem?

**Comment by yon86** [comment]
@mkiisoft  it works u have to have this at the root of your activity element  xmlns:app="http://schemas.android.com/apk/res-auto" android studio generated a code that didn't work and I had to change it to this to work properly

**Comment by 81813780** [comment]
See #45

**Comment by mohopa** [comment]
hi,
color still not change in version 2.1.3
thank you
