### ISSUE TITLE
Your apk is about 1.3m large

### ISSUE THREAD

**Issue by Winghin2517** [81813780/AVLoadingIndicatorView#40]
Hello

I have included your library in my app, I just love the look and feel of your loading indicators. However, after including the library, I noticed a dramatic increase in the size of my app. I think the reason is that you have package all the indicators into your library so even if I only use ball pulse in my app, I'm still getting all the rest of the indicators that I don't really need. Is there a way I can extract out just the ball pulse and include that into my app as I don't need the other indicators?

**Comment by 4xes** [comment]
No, indicators is small part of size. The library use [nineoldandroids](https://github.com/JakeWharton/NineOldAndroids) for animation and support old version Android which bigger then AVLoadingIndicatorView. You can copy implementation in your project and remove unused code and dependency of [nineoldandroids](https://github.com/JakeWharton/NineOldAndroids).

**Comment by Winghin2517** [comment]
I actually did this and it worked. Thanks!

I don't need support up to api 7 so it just made sense for me to remove
nineoldandroid
