### ISSUE TITLE
在下拉刷新和上拉加载布局中使用该库导致Crash

### ISSUE THREAD

**Issue by cizkey** [81813780/AVLoadingIndicatorView#41]
我在下拉刷新和上拉加载的头脚布局中使用该库,会导致crash.

使用方式为:
```java
    <com.wang.avi.AVLoadingIndicatorView
            android:id="@+id/header_progressbar"
            xmlns:app="http://schemas.android.com/apk/res-auto"
            android:layout_width="25dp"
            android:layout_height="25dp"
            android:layout_centerVertical="true"
            android:layout_toLeftOf="@+id/header_text"
            android:layout_toStartOf="@+id/header_text"
            android:visibility="invisible"
            app:indicator="BallSpinFadeLoader"
            app:indicator_color="@color/gray_88808080"
            />
```
在代码中仅作了显示和隐藏. 未做其他操作. 
结果打开app进入列表就发现主线程阻塞了. 最终导致crash.
crash日志如下:
![日志1](https://cloud.githubusercontent.com/assets/14026236/16217507/9f91bc06-37a6-11e6-9ee8-2cf389febf46.jpg)
![日志2](https://cloud.githubusercontent.com/assets/14026236/16217514/abdd3936-37a6-11e6-9e6b-8b0db5f465c8.jpg)

**Comment by 81813780** [comment]
我在另一个项目**[Dribbbler](https://github.com/81813780/Dribbbler)**使用了该库作为加载更多,但是并没有出现问题.

![Dribbbler](http://o8wshxdfk.bkt.clouddn.com/Screenshot_2016-06-21-18-07-32-096_com.wang.dribb.png) 

可以提供详细一点的代码吗？比如下拉刷新和加载更多那里的代码 .

**Comment by cizkey** [comment]
我是有一个这样的页面.  请求网络时显示"数据加载中"的对话框, 然后数据加载完毕有下拉刷新和上拉加载.
总共在这三处使用该库的AVLoadingIndicatorView的BallSpinFadeLoader样式.

![现在该图中并非此库效果](https://cloud.githubusercontent.com/assets/14026236/16264833/69b1dd10-38ae-11e6-8f7f-cf284cb60c30.png)

正如我上文描述, 只是初级的使用方式, 在xml中引入控件
```java
 <com.wang.avi.AVLoadingIndicatorView
            android:id="@+id/header_progressbar"
            xmlns:app="http://schemas.android.com/apk/res-auto"
            android:layout_width="25dp"
            android:layout_height="25dp"
            android:layout_centerVertical="true"
            android:layout_toLeftOf="@+id/header_text"
            android:layout_toStartOf="@+id/header_text"
            android:visibility="invisible"
            app:indicator="BallSpinFadeLoader"
            app:indicator_color="@color/gray_88808080"
            />
```
在下拉刷新和上拉加载时, 松开时显示如下效果
![松开时显示效果](https://cloud.githubusercontent.com/assets/14026236/16264995/75b8eabc-38af-11e6-87da-9a81a2ab9a74.jpg)
对该控件操作的代码为
```java
  @Override
    public void onStartAnim() {
        headerTitle.setText("正在刷新");
        headerArrow.setVisibility(View.INVISIBLE);
        headerArrow.clearAnimation();
        headerProgressbar.setVisibility(View.VISIBLE);    ///这里就是AVLoadingIndicatorView控件
    }

    @Override
    public void onFinishAnim() {
        headerTitle.setText("下拉刷新");
        headerArrow.setVisibility(View.VISIBLE);
        headerProgressbar.setVisibility(View.INVISIBLE);  ///这里就是AVLoadingIndicatorView控件
    }
```
使用下拉刷新和上拉加载框架为 SpringView  (github地址:https://github.com/liaoinstan/SpringView)

使用BallSpinFadeLoader样式的进度条后, 在进入上图页面, 数据加载完毕后, 列表的整个页面就卡死了. 然后我触摸屏幕就报出crash了.  Crash信息就是我最开始贴图信息.
 
现在我暂时使用其他的库(SpinKitView)来代替, 并未出现crash现象.因此推测可能是该库可能有些许bug, 或者该库可能和SpringView库不兼容. 

使用系统版本: 4.4.2

**Comment by cizkey** [comment]
忘记说了, 最开始我只加在下拉刷新中是没问题的.  后来再加到下拉加载更多时就crash了.  我在想会不会是在多处同时使用造成的.

**Comment by 81813780** [comment]
好的，我检查下。

**Comment by 81813780** [comment]
See #45
