### ISSUE TITLE
AVLoadingIndicatorView无法在代码里动态构造问题

### ISSUE THREAD

**Issue by JackRo** [81813780/AVLoadingIndicatorView#47]
`       BallBeatIndicator ballBeatIndicator = new BallBeatIndicator();
        AVLoadingIndicatorView avLoadingIndicatorView = new AVLoadingIndicatorView(this);
        avLoadingIndicatorView.setIndicator(ballBeatIndicator);
        avLoadingIndicatorView.setIndicatorColor(0xffffff);`

我这里动态构造抛出下面的异常

`java.lang.NullPointerException: Attempt to invoke virtual method 'void com.wang.avi.Indicator.setColor(int)' on a null object reference`

是因为AVLoadingIndicatorView在构造函数里没给indicatorName一个默认值：

`        String indicatorName=a.getString(R.styleable.AVLoadingIndicatorView_indicatorName);
        int indicatorColor=a.getColor(R.styleable.AVLoadingIndicatorView_indicatorColor, Color.WHITE);
        setIndicator(indicatorName); //这里没有默认值
        setIndicatorColor(indicatorColor); //导致这里空指针异常
`

**Comment by 81813780** [comment]
好的，我检查一下。

**Comment by 81813780** [comment]
已修复，希望你可以帮我测试一下。你需要更新至最新版本`compile 'com.wang.avi:library:2.1.2'` ，如有问题，欢迎告诉我，谢谢  @JackRo

**Comment by ProZoom** [comment]
最新版2.1.3又有这个问题了！降为2.1.2没问题，最新版怎么回事呢？
