### ISSUE TITLE
颜色问题

### ISSUE THREAD

**Issue by HardyHaclke** [81813780/AVLoadingIndicatorView#48]
为啥用indicatorColor这个属性设置颜色为黑色，但显示的照样是白色
代码如下：
<com.wang.avi.AVLoadingIndicatorView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/indicator"
        android:layout_gravity="center"
        style="@style/AVLoadingIndicatorView.Large"
        app:indicatorName="BallPulseIndicator"
        app:indicatorColor="#000000"/>

**Comment by HardyHaclke** [comment]
我发现了原来颜色给写死了，只能是白色。
int indicatorColor=a.getColor(R.styleable.AVLoadingIndicatorView_indicatorColor, Color.WHITE);

**Comment by 81813780** [comment]
已修复，你可以试试。有问题再和我说 :)
