### ISSUE TITLE
如何在baseactvity添加呢，不想重复在布局里面写

### ISSUE THREAD

**Issue by catroom** [81813780/AVLoadingIndicatorView#49]
虽然问得有点小白，我不想在每个layout下添加loadingview，我想在基类里面添加，求回复，谢谢

**Comment by 81813780** [comment]
其实你这个问题等同于如何在基类添加 `Toolbar`  , 而不用每次在 `layout` 里写 .

这里 , 我提供两个思路 , 具体实现细节你可以 Google ;
1、在 `BaseActivity` 中通过代码添加 `AVLoadingIndicatorView` .
2、单独定义一个 `layout` 文件 , 例如 `view_avloadingindicator.xml` , 然后每次在布局中 include .

**Comment by catroom** [comment]
谢谢回复

**Comment by 81813780** [comment]
不客气 :)
