### ISSUE TITLE
No resource identifier found for attribute 'indicatorName' in package 'xxx'

### ISSUE THREAD

**Issue by gosttusng** [81813780/AVLoadingIndicatorView#52]
使用2.1.3版本

1. 在一个lib module A中添加avloading，生成arr：
`<com.wang.avi.AVLoadingIndicatorView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginRight="14dp"
            app:indicatorName="LineScale"
            app:indicatorColor="#FFE75764"
            />`
    在布局根属性中添加了`xmlns:app="http://schemas.android.com/apk/res-auto"`

2. 在项目的主要module中添加A.arr,编译报错：
`Error:(13) No resource identifier found for attribute 'indicatorName' in package 'atide.ms.myapp'`

请求帮助，谢谢

**Comment by 81813780** [comment]
对比下你的indicatorName名字，正确的名字应该是：
`app:indicatorName="LineScaleIndicator"`
